# Generated by Django 4.1.7 on 2023-03-29 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=11)),
                ('antecedentes', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('epicrisis', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('diagnostico', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('tratamientos', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('recomendaciones', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
