# Generated by Django 4.1.7 on 2023-03-01 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_cedula'),
        ('Core', '0004_alter_historia_clinica_antecedentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiaclinica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('antecedentes', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('epicrisis', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('diagnostico', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('tratamientos', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('recomendaciones', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Historia_Clinica',
        ),
    ]
