# Generated by Django 4.1.7 on 2023-05-06 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_historiaclinica_antecedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
