# Generated by Django 4.1.7 on 2023-05-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_historiaclinica_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='date_joined',
            new_name='Fecha_Registro',
        ),
    ]
