# Generated by Django 4.1.7 on 2023-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_rename_date_joined_historiaclinica_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.CharField(blank=True, help_text='Este campo no es de carácter obligatorio y depende de la condición de cada paciente.', max_length=10000, null=True, unique=True, verbose_name='Diagnóstico'),
        ),
    ]
