# Generated by Django 4.1.7 on 2023-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.FloatField(),
        ),
    ]
