# Generated by Django 4.1.7 on 2023-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='user',
            name='is_especialista',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Especialista status'),
        ),
    ]
