# Generated by Django 4.1.7 on 2023-04-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_user_rol_user_is_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_especialista',
            field=models.BooleanField(default=False, verbose_name='Especialista status'),
        ),
    ]
