# Generated by Django 4.1.7 on 2023-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_is_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(help_text='Requerido. Únicamente números. Sin puntos ni comas', max_length=11, verbose_name='Cédula'),
        ),
    ]
