# Generated by Django 4.1.7 on 2023-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_default.png', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_especialista',
            field=models.BooleanField(default=False, verbose_name='Rol especialista'),
        ),
    ]
