# Generated by Django 4.1.7 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_user_picture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='imagen-base.png', upload_to='user/'),
        ),
    ]
