# Generated by Django 4.1.7 on 2023-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='imagen_base.png', upload_to='users/', verbose_name='Foto de Perfil'),
        ),
    ]
